import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Combobox } from "@/components/ui/ComboBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex text-white items-center p-4 py-8 justify-between h-[5vw] bg-gray-600 w-screen top-0 sticky">
          <div className=" w-[8vw]">Malik ↗</div>
          <Combobox />
          <div className=" text-end w-[8vw]">hi</div>
        </nav>
        {children}
      </body>
    </html>
  );
}
