import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Combobox } from "@/components/ui/ComboBox";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Malik's Demos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex text-white items-center p-4 py-8 justify-between h-[5vw] bg-gray-600 w-screen top-0 sticky">
          <a href="https://malikkotb.github.io/blog/" target="_blank" className="w-[8vw]">Malik ↗</a>
          <Combobox />
          <div className=" justify-end items-center flex w-[8vw]"><img alt="logo" width={36} height={36} src={"./Ellipse.png"} /></div>
        </nav>
        {children}
      </body>
    </html>
  );
}
